language: node_js
sudo: false
node_js: 8
cache:
  directories:
    - node_modules
before_script:
- node --version
- npm --version
script:
- npm run test-travis
- if [[ $TRAVIS_PULL_REQUEST == "false" ]]; then npm run test-saucelabs; fi
- if [[ $TRAVIS_PULL_REQUEST == "false" ]]; then pkill node; fi
after_success:
- npm run coveralls
